"""Deterministic generators for command-output conformance fixtures.

These generators produce raw byte payloads that mirror the acceptance scenarios
in ``acceptance/SCENARIOS.md``.  They are deterministic and record how many
fixtures they have generated so tests can prove fixtures are replayable.
"""

from __future__ import annotations

import random
import string
from collections.abc import Callable
from dataclasses import dataclass


@dataclass(frozen=True)
class GeneratedFixture:
    """A generated fixture with metadata useful for comparisons."""

    name: str
    stdout: bytes
    stderr: bytes
    exit_code: int
    invocation: int


class FixtureGenerator:
    """Deterministic generator for command-output fixtures.

    Each generation method increments an invocation counter and uses the
    seeded RNG so that repeated runs produce byte-identical output.
    """

    _TOKEN_ESTIMATE_RATIO = 4

    def __init__(self, seed: int = 42) -> None:
        self._rng = random.Random(seed)
        self._invocation_count = 0

    @property
    def invocation_count(self) -> int:
        """Number of fixture payloads generated by this instance."""
        return self._invocation_count

    def _bump(self) -> int:
        self._invocation_count += 1
        return self._invocation_count

    def _text(self, size: int) -> str:
        """Return ``size`` random ASCII letters/spaces/newlines."""
        chars = string.ascii_letters + " " * 7 + "\n"
        return "".join(self._rng.choices(chars, k=size))

    def small_stdout(self, lines: int = 20) -> GeneratedFixture:
        """A.01 — small stdout, exit 0."""
        invocation = self._bump()
        payload = b"".join(f"line {i:03d}\n".encode() for i in range(lines))
        return GeneratedFixture("small_stdout", payload, b"", 0, invocation)

    def small_stderr_nonzero(self, lines: int = 5, exit_code: int = 7) -> GeneratedFixture:
        """A.02 — diagnostics on stderr, nonzero exit."""
        invocation = self._bump()
        payload = b"".join(f"error {i:03d}\n".encode() for i in range(lines))
        return GeneratedFixture("small_stderr_nonzero", b"", payload, exit_code, invocation)

    def large_stdout(
        self,
        lines: int = 100_000,
        marker: str = "UNIQUE-MIDDLE-MARKER",
    ) -> GeneratedFixture:
        """A.03 — large numbered stdout with a unique middle marker."""
        invocation = self._bump()
        middle = lines // 2
        parts: list[bytes] = []
        for i in range(lines):
            if i == middle:
                parts.append(f"{marker} at line {middle}\n".encode())
            else:
                parts.append(f"line {i:06d}\n".encode())
        return GeneratedFixture("large_stdout", b"".join(parts), b"", 0, invocation)

    def mixed_streams(
        self,
        stdout_lines: int = 50_000,
        stderr_lines: int = 1_000,
    ) -> GeneratedFixture:
        """A.04 — large data on both stdout and stderr."""
        invocation = self._bump()
        out = b"".join(f"out {i:06d}\n".encode() for i in range(stdout_lines))
        err = b"".join(f"err {i:05d}\n".encode() for i in range(stderr_lines))
        return GeneratedFixture("mixed_streams", out, err, 0, invocation)

    def failure_buried_in_noise(
        self,
        passing: int = 20_000,
        cleanup: int = 5_000,
    ) -> GeneratedFixture:
        """A.05 — many passing lines, a traceback, then cleanup, exit 1."""
        invocation = self._bump()
        failure_line = passing // 2
        parts: list[bytes] = []
        for i in range(passing + cleanup + 1):
            if i == failure_line:
                parts.append(
                    (
                        b"Traceback (most recent call last):\n"
                        b'  File "demo.py", line 42, in <module>\n'
                        b"    raise RuntimeError('simulated failure')\n"
                        b"RuntimeError: simulated failure\n"
                    ),
                )
            elif i < passing:
                parts.append(f"passing test {i:05d}\n".encode())
            else:
                parts.append(f"cleanup {i - passing:05d}\n".encode())
        return GeneratedFixture("failure_buried_in_noise", b"".join(parts), b"", 1, invocation)

    def repeated_line(
        self,
        line: bytes = b"repeated line",
        count: int = 10_000,
    ) -> GeneratedFixture:
        """B.01 — the same line repeated many times."""
        invocation = self._bump()
        payload = (line + b"\n") * count
        return GeneratedFixture("repeated_line", payload, b"", 0, invocation)

    def carriage_return_progress(self, count: int = 10_000) -> GeneratedFixture:
        """B.02 — carriage-return progress updates ending in success."""
        invocation = self._bump()
        parts: list[bytes] = []
        for i in range(count):
            parts.append(f"\rprogress {i + 1}/{count}".encode())
        parts.append(b"\rfinal: success\n")
        return GeneratedFixture("carriage_return_progress", b"".join(parts), b"", 0, invocation)

    def giant_line(self, size: int = 5 * 1024 * 1024) -> GeneratedFixture:
        """B.03 — a single very long line."""
        invocation = self._bump()
        payload = b"x" * size + b"\n"
        return GeneratedFixture("giant_line", payload, b"", 0, invocation)

    def invalid_utf8(self) -> GeneratedFixture:
        """B.04 — invalid UTF-8 bytes."""
        invocation = self._bump()
        payload = b"valid prefix\xff\xfevalid suffix\n"
        return GeneratedFixture("invalid_utf8", payload, b"", 0, invocation)

    def binary_output(self, size: int = 10_000) -> GeneratedFixture:
        """B.05 — NUL-rich random bytes."""
        invocation = self._bump()
        payload = bytes(self._rng.randint(0, 255) for _ in range(size))
        return GeneratedFixture("binary_output", payload, b"", 0, invocation)

    def secret_in_output(self, secret: str = "harness-secret-token-abc123") -> GeneratedFixture:
        """E.01 — output containing a registered secret value."""
        invocation = self._bump()
        payload = (
            f"connecting with token={secret}\n"
            "operation completed\n"
        ).encode()
        return GeneratedFixture("secret_in_output", payload, b"", 0, invocation)

    def split_secret(self, secret: str = "harness-secret-token-abc123") -> GeneratedFixture:
        """E.02 — a secret positioned so it spans typical read chunk boundaries."""
        invocation = self._bump()
        chunk_size = 64 * 1024
        prefix = b"x" * (chunk_size - 10)
        payload = prefix + secret.encode() + b"\n"
        return GeneratedFixture("split_secret", payload, b"", 0, invocation)

    def ansi_osc_output(self) -> GeneratedFixture:
        """E.03 — terminal escape and hyperlink sequences."""
        invocation = self._bump()
        payload = (
            b"\x1b]0;evil title\x07"
            b"\x1b[31mred text\x1b[0m"
            b"\x1b]8;;https://example.com\x07link\x1b]8;;\x07"
            b"\x1b[2J\rcleared\n"
        )
        return GeneratedFixture("ansi_osc_output", payload, b"", 0, invocation)

    def long_session_class(self, target_tokens: int = 178_800) -> GeneratedFixture:
        """G.01 — representative long-session corpus.

        Generates enough text to approximate ``target_tokens`` using the
        configured bytes-per-token estimate.
        """
        invocation = self._bump()
        target_bytes = target_tokens * self._TOKEN_ESTIMATE_RATIO
        lines: list[str] = []
        line_no = 0
        while sum(len(line.encode("utf-8")) for line in lines) < target_bytes:
            lines.append(
                f"[{line_no:05d}] bash result: "
                f"{self._text(self._rng.randint(40, 120)).strip()}"
            )
            line_no += 1
        payload = "\n".join(lines).encode("utf-8") + b"\n"
        return GeneratedFixture("long_session_class", payload, b"", 0, invocation)

    def generate_all(self) -> list[GeneratedFixture]:
        """Generate every fixture type once, in deterministic order."""
        methods: list[Callable[[], GeneratedFixture]] = [
            self.small_stdout,
            self.small_stderr_nonzero,
            self.large_stdout,
            self.mixed_streams,
            self.failure_buried_in_noise,
            self.repeated_line,
            self.carriage_return_progress,
            self.giant_line,
            self.invalid_utf8,
            self.binary_output,
            self.secret_in_output,
            self.split_secret,
            self.ansi_osc_output,
            self.long_session_class,
        ]
        return [method() for method in methods]
