"""Python control-plane contracts for the non-executing v2 boundary.

This namespace is deliberately independent of the v1 capture and projection
engine.  It can be imported by a native-engine selector or policy compiler
without starting the reference engine's import graph.
"""

from outctl.control.contracts import (
    CapabilityNegotiationError,
    CapabilityRequirement,
    CaptureCommitment,
    CaptureDurability,
    CommandScope,
    EngineCapabilities,
    EngineFeature,
    EngineIdentity,
    NegotiatedCapabilities,
    PolicyBinding,
    PolicyCacheEntry,
    PolicySnapshot,
    SinkPolicy,
    negotiate_capabilities,
)
from outctl.control.policy import (
    ClaimProvenance,
    ClaimProvenanceRecord,
    CommissioningContext,
    CommissioningProvenance,
    CompiledPolicy,
    PolicyCompileError,
    PolicyDiagnostic,
    PolicyExplanation,
    PolicyLintResult,
    PolicySourcePathError,
    ProtectedSecretRegistry,
    SecretRegistryError,
    canonical_policy_material,
    commissioning_context_from_dict,
    commissioning_provenance_digest,
    compile_policy_source,
    explain_policy,
    lint_policy_source,
)

__all__ = [
    "CapabilityNegotiationError",
    "CapabilityRequirement",
    "ClaimProvenance",
    "ClaimProvenanceRecord",
    "CommissioningContext",
    "CommissioningProvenance",
    "CompiledPolicy",
    "CommandScope",
    "CaptureCommitment",
    "CaptureDurability",
    "EngineCapabilities",
    "EngineFeature",
    "EngineIdentity",
    "NegotiatedCapabilities",
    "PolicyBinding",
    "PolicyCacheEntry",
    "PolicyCompileError",
    "PolicyDiagnostic",
    "PolicyExplanation",
    "PolicyLintResult",
    "PolicySnapshot",
    "PolicySourcePathError",
    "ProtectedSecretRegistry",
    "SecretRegistryError",
    "SinkPolicy",
    "canonical_policy_material",
    "commissioning_context_from_dict",
    "commissioning_provenance_digest",
    "compile_policy_source",
    "explain_policy",
    "lint_policy_source",
    "negotiate_capabilities",
]
